### ISSUE TITLE
Error with version 1.0.1

### ISSUE THREAD

**Issue by rlee1990** [FooStudio/flutter_statusbar_manager#1]
I receive the following error when trying to run on Android: error: package tandroid.animation does not exist
import tandroid.animation.ArgbEvaluator;

* What went wrong:
Execution failed for task ':flutter_statusbar_manager:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
Finished with error: Gradle build failed: 1

**Comment by mendieta** [comment]
Hi, thank you for noticing this issue. I will try to upload a fix today , if not tomorrow morning it will be fixed on pub.

**Comment by rlee1990** [comment]
@mendieta thanks

**Comment by mendieta** [comment]
@rlee1990 I have published a new version to pub, and updated the repository. If anything else pops out don't hesitate to open another issue. Closing this issue

**Comment by rlee1990** [comment]
@mendieta Thanks. It's all working now.
