### ISSUE TITLE
Support androidx

### ISSUE THREAD

**Issue by HosseinArabbeigi** [FooStudio/flutter_statusbar_manager#11]
Please add support for androidx.

**Comment by vAugagneur** [comment]
up

**Comment by kyungjoongo** [comment]
Please add support for androidx.

**Comment by vAugagneur** [comment]
Please can you give us some news ? Are you going to add support for androidx ?
Best regards

**Comment by chenxianqi** [comment]
Ditto ， Need to point out AndroidX

**Comment by H03in** [comment]
you can use guitcastro commits in [this](https://github.com/FooStudio/flutter_statusbar_manager/pull/4) issue to migrate to androidx.

**Comment by vAugagneur** [comment]
Thanks for your answer @H03in , do you know where to locate local repository to merge guitcastro commits ?

**Comment by H03in** [comment]
Your welcome @vAugagneur, it doesn't need to pull commits, just add commits changes to your flutter plugin inside your project, using IDE, for example in android studio, this is my status bar plugin : 

![image](https://user-images.githubusercontent.com/12210646/56432906-53d45280-62e4-11e9-9da9-9f678f785fb9.png)

**Comment by vAugagneur** [comment]
thanks @H03in (y)

**Comment by gustavobrian** [comment]
any easy solution? thanks...

**Comment by matthewrice345** [comment]
You can use guitcastro's master version by adding the following to you pubspec.yaml
```
flutter_statusbar_manager:
    git: git@github.com:guitcastro/flutter_statusbar_manager.git
```

**Comment by idjugostran** [comment]
Me helped Android Studio > Refactor Menu > Migrate to AndroidX
 https://stackoverflow.com/questions/51280090/what-is-androidx

**Comment by isikxd** [comment]
@g-balas you need to set up ssh keys with github or just use https:
```
flutter_statusbar_manager:
    git: https://github.com/guitcastro/flutter_statusbar_manager.git
```

**Comment by mojimich2015** [comment]
Please ass support for androidX . 
I upgraded my flutter project to androidX , but when i wantd to build a release apk , i got this error : 
```
A problem occurred configuring root project 'flutter_statusbar_manager'.
> Failed to notify project evaluation listener.
   > org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(Ljava/lang/String;)V

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s


The plugin flutter_statusbar_manager could not be built due to the issue above. 
```

I think this is because of android x incompatibility .

**Comment by quetool** [comment]
> Please add support for androidX .
> I upgraded my flutter project to androidX , but when i wantd to build a release apk , i got this error :
> 
> ```
> A problem occurred configuring root project 'flutter_statusbar_manager'.
> > Failed to notify project evaluation listener.
>    > org.gradle.api.tasks.compile.CompileOptions.setBootClasspath(Ljava/lang/String;)V
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 2s
> 
> 
> The plugin flutter_statusbar_manager could not be built due to the issue above. 
> ```
> 
> I think this is because of android x incompatibility .

Did you read this entire thread?

**Comment by samuelematias** [comment]
Dependency problem with `androidx.localbroadcastmanager:localbroadcastmanager`
<img width="877" alt="Screen Shot 2019-12-03 at 15 43 51" src="https://user-images.githubusercontent.com/5155386/70079612-d72c8500-15e3-11ea-9355-b7d77dbc6380.png">

`Flutter 1.9.1+hotfix.6 • channel stable`
`Dart 2.5.0`

**Comment by klaszlo8207** [comment]
Android dependency 'androidx.lifecycle:lifecycle-runtime' has different version for the compile (2.0.0-rc01) and runtime (2.0.0) classpath. You should manually set the same version via DependencyResolution

**Comment by YAPPDEF** [comment]
Why does it take so long to fix this?

**Comment by rafaelmaeuer** [comment]
Will there be a fix in the future or should we keep guitcastro's fork as permanent solution?

**Comment by mendieta** [comment]
This should be fixed now
