### ISSUE TITLE
Can hide the status bar at the bottom?

### ISSUE THREAD

**Issue by xiongsongsong** [FooStudio/flutter_statusbar_manager#2]
![123](https://user-images.githubusercontent.com/342509/45609892-71aab200-ba8c-11e8-8bc5-db8e6e337e23.png)

Can hide the status bar at the bottom?

thanks.

**Comment by xiongsongsong** [comment]
this is system info.

![screenshot_2018-09-17-15-18-44-618_com android se](https://user-images.githubusercontent.com/342509/45610448-85efae80-ba8e-11e8-8ee7-e6320f7b7d01.png)

**Comment by mendieta** [comment]
Let me take a look at this, will get back to you in a few hours.

**Comment by xiongsongsong** [comment]
@mendieta Thanks!

**Comment by mendieta** [comment]
I think this has to do with custom Android UIs
