### ISSUE TITLE
StatusBarStyle does not change

### ISSUE THREAD

**Issue by JUSTIVE** [FooStudio/flutter_statusbar_manager#3]
I'm using Google Pixel 3 (with Android P), and the following code didn't change my status bar theme.

```dart
//~ inside of State<MyApp>/initState method
FlutterStatusbarManager.setStyle(StatusBarStyle.DARK_CONTENT);
```
I've tried `StatusBarStyle.DARK_CONTENT` and also `StatusBarStyle.LIGHT_CONTENT` and both of them showed white status bar icons.

thanks.

**Comment by mendieta** [comment]
This should be working now
