### ISSUE TITLE
error: package android.support.v4.view does not exist

### ISSUE THREAD

**Issue by DebkanchanSamadder** [FooStudio/flutter_statusbar_manager#8]
This issue seems to occur only on AndroidX. I've migrated my code to AndroidX. This can be resolved by importing `import androidx.core.view.ViewCompat` in your main java file. I'm no android dev so I don't know how to exactly resolve this but if possible please implement a method which import correct things for the correct platform.

**Comment by rafaelmaeuer** [comment]
Might be related with issue #11 try out solution from [this](https://github.com/FooStudio/flutter_statusbar_manager/issues/11#issuecomment-488792276) comment.

**Comment by mendieta** [comment]
This should be fixed now
